# This is a basic workflow to help you get started with Actions

name: (test) android

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      bundle_tag:
        description: 'package version tag'
        required: false

      deps_package_tag:
        description: 'deps package tag'
        type: string
        required: true
        default: "v8_12.4.254.21_r13"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prebuilt_android:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: godotengine/godot
          path: godot
          ref: 4.3

      - uses: actions/checkout@v4
        with:
          repository: ialex32x/GodotJS
          path: godot/modules/GodotJS
          lfs: true
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Deps
        run: |
          Invoke-WebRequest -Uri https://github.com/ialex32x/GodotJS-Dependencies/releases/download/${{ github.event.inputs.deps_package_tag }}/${{ github.event.inputs.deps_package_tag }}.zip -OutFile v8.zip
          dir v8.zip
          7z x -ogodot/modules/GodotJS v8.zip
          dir godot/modules/GodotJS/v8
  
      # Runs a single command using the runners shell
      - name: Prerequisites
        run: |
          pip install scons

      # Runs a set of commands using the runners shell
      - name: Build Godot
        shell: cmd
        run: |
          echo %JAVA_HOME_17_X64%

          SET JAVA_HOME=%JAVA_HOME_17_X64%
          SET ANDROID_API_LEVEL=24

          cd godot

          scons p=android target=template_debug   ndk_platform=android-%ANDROID_API_LEVEL% arch=x86_64 deprecated=no 
          scons p=android target=template_debug   ndk_platform=android-%ANDROID_API_LEVEL% arch=arm64  deprecated=no generate_apk=yes 

          scons p=android target=template_release ndk_platform=android-%ANDROID_API_LEVEL% arch=x86_64 deprecated=no 
          scons p=android target=template_release ndk_platform=android-%ANDROID_API_LEVEL% arch=arm64  deprecated=no generate_apk=yes 

      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: prebuilt_android
          path: godot/bin/*.*
