# This is a basic workflow to help you get started with Actions

name: (test) web

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      bundle_tag:
        description: 'package version tag'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prebuilt_godot_editor_web:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: godotengine/godot
          path: godot
          ref: 4.3

      - uses: actions/checkout@v4
        with:
          repository: ialex32x/GodotJS
          path: godot/modules/GodotJS
          lfs: true

      - uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Runs a single command using the runners shell
      - name: Prerequisites
        run: |
          pip install scons

      # Runs a set of commands using the runners shell
      - name: Build Godot
        run: |
          SET EMSDK_PATH=$GITHUB_WORKSPACE\emsdk
          CALL %EMSDK_PATH%\emsdk.bat update
          SET EMSDK_VERSION=3.1.64
          CALL %EMSDK_PATH%\emsdk.bat install %EMSDK_VERSION%
          CALL %EMSDK_PATH%\emsdk.bat activate %EMSDK_VERSION%
          CALL %EMSDK_PATH%\emsdk_env.bat

          cd godot
          scons dev_build=yes optimize=debug p=web deprecated=no target=template_debug lto=none use_assertions=no use_safe_heap=yes
          scons dev_build=no p=web deprecated=no target=template_release lto=auto use_assertions=no use_safe_heap=no

      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: prebuilt_godot_editor_web
          path: godot/bin/*.*
