name: (test) macos jsc

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      godotjs_tag:
        description: 'GodotJS version tag'
        type: string
        required: true

      godot_branch:
        description: 'godot branch'
        type: string
        required: true
        default: "4.3"

      deps_package_tag:
        description: 'deps package tag'
        type: string
        required: true
        default: "v8_12.4.254.21_r13"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  editor_macos_arm64_jsc:
    # The type of runner that the job will run on
    runs-on: macos-15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: godotengine/godot
          path: godot
          ref: ${{ github.event.inputs.godot_branch }}

      - uses: actions/checkout@v4
        with:
          repository: ialex32x/GodotJS
          path: godot/modules/GodotJS
          lfs: true
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Runs a single command using the runners shell
      - name: Prerequisites
        run: pip install scons

      - name: Build Deps
        run: |
          curl -L https://github.com/ialex32x/GodotJS-Dependencies/releases/download/${{ github.event.inputs.deps_package_tag }}/${{ github.event.inputs.deps_package_tag }}.zip --output v8.zip
          7z x -ogodot/modules/GodotJS v8.zip
          sh godot/misc/scripts/install_vulkan_sdk_macos.sh

      # Runs a set of commands using the runners shell
      - name: Build for arm64
        run: |
          cd godot
          scons dev_build=yes p=macos arch=arm64 use_jsc=yes
  
      - name: Prepare artifact
        run: |
          strip godot/bin/godot.*
          chmod +x godot/bin/godot.*
          7z a -tzip editor_macos_arm64_jsc.zip godot/bin/
  
      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: editor_macos_arm64_jsc
          path: editor_macos_arm64_jsc.zip

